trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/Cypress
  CYPRESS_PAT: $(CYPRESS_PAT) # je PAT via DevOps Pipeline secrets

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install NPM dependencies'

  - script: |
      npx cypress verify
    displayName: 'Verify Cypress installation'

  - script: |
      npx cypress run --spec "cypress/e2e/test-dev-azure-pipeline.cy.js"
    displayName: 'Run Cypress test'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/results/*.xml'
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: cypress/videos
      artifact: cypress-videos

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: cypress/screenshots
      artifact: cypress-screenshots
